apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - object-storage.yaml
    - object-storage-b2.yaml
    - jira-cluster.yaml
    - jira-monitor.yaml
    - jira-backup.yaml
