apiVersion: v1
kind: Service
metadata:
    name: ejbca-loadbalancer
    namespace: ejbca
    annotations:
        external-dns.alpha.kubernetes.io/hostname: ejbca.axiom.lucasfehres.nl
spec:
    type: LoadBalancer
    ports:
        - name: https
          port: 443
          targetPort: 8082
          protocol: TCP
    selector:
        app.kubernetes.io/instance: ejbca
        app.kubernetes.io/name: ejbca
