apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - cluster.yaml
    - object-storage.yaml
    - object-storage-b2.yaml
    - monitor.yaml
    - backup.yaml
    - tcproute.yaml
