apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - crds.yaml
    # - rke2.yaml
    # - podmonitor.yaml
    - namespace.yaml
    # - wg-exporter.yaml
    # - wg-exporter-role.yaml
