apiVersion: networking.liqo.io/v1beta1
kind: Configuration
metadata:
    labels:
        liqo.io/remote-cluster-id: chaos
    name: chaos
    namespace: liqo-tenant-chaos
spec:
    remote:
        cidr:
            external:
                - 10.70.0.0/16
            pod:
                # this one is service, idk
                - 10.21.0.0/16
                -  # actual pod ranges
                - 10.20.0.0/16
                - 10.0.0.0/16
