apiVersion: networking.liqo.io/v1beta1
kind: Configuration
metadata:
    labels:
        liqo.io/remote-cluster-id: chaos-2
    name: chaos-2
    namespace: liqo-tenant-chaos-2
spec:
    remote:
        cidr:
            external:
                - 10.70.0.0/16
            pod:
                - 10.0.0.0/16
