apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - server-gateway.yaml
    - configuration.yaml
    - resourceslice.yaml
    - offloaded-namespace.yaml
    - namespaceoffloading.yaml
