apiVersion: v1
kind: Service
metadata:
    name: jira
    namespace: atlassian
spec:
    selector:
        app: jira
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
    type: ClusterIP
